site_name: VketCloudSDK Manual
site_description: 'VketCloudSDKのマニュアルです'
site_author: 'HIKKY'

theme:
  feature:
    tabs: true
  name: material
  palette:
    accent: Green
    primary: Green
  features:
    - navigation.indexes
    #- navigation.expand

extra:
  version:
    provider: mike
    default: latest
  search:
    language: 'en'
    language: 'ja'

use_directory_urls: false

plugins:
  - search:
  - mike:
      version_selector: true
      css_dir: css
      javascript_dir: js
      canonical_version: null
  - i18n:
      default_language: ja
      languages:
        en: English
        ja: 日本語
      nav_translations:
        ja:
          Introduction: はじめに
          About VketCloudSDK: VketCloudSDKについて
          Setup Account: アカウント準備
          Operating Environment: Unity事前設定
          Build And Run: ビルド方法
          World Upload: ワールドアップロード
          Setup SDK(external): SDKの導入方法
          Var: 変数・値
          Operator: 演算子
          Class: クラス・構造体
          Component: コンポーネント
          Built-in Class: 組み込みクラス
          Vector3: Vector3構造体
          Quaternion: Quaternion構造体
          Matrix: Matrix構造体
          Item: Itemクラス
          Player: Playerクラス
          System Function: 組み込み・システム関数
          HEOExporter Overview: HEOExporter概要
          HEOExporter Tutorial: HEOExporterチュートリアル
          Unity Guidelines : Unity制作ガイドライン
          ReflectionProbe: リフレクションプローブ
          Texture Compression: テクスチャ圧縮
          Get closer to the look of VketCloud to Unity: UnityとVketCloudの見た目を揃える
          Mesh Collider: メッシュコライダーについて
          HEOComponent: HEOコンポーネントの使い方
          About VketCloudSDK: VketCloudSDKについて
          OperatingEnvironment: 動作環境
          SetupSDK: 導入方法
          BuildAndRun: ビルド
          WorldUpload: アップロード
          License: 利用規約
          Loading stops: ブラウザの読み込みが止まる
          Actions: Actionクラス
          Actions Overview: アクションの概要
          Particle Editor : パーティクルエディター
          ParticleEditor Overview: パーティクルエディター概要 
          About Screen: 操作画面について
          Operation: 操作説明
          Window Info: ウィンドウ解説
          Toolbar: ツールバー
          Property: プロパティウィンドウ
          Trouble shooting: トラブルシューティング
          Build Error: ビルドエラー
          Browser is not open: ブラウザが立ち上がらない
          Changes are not applied: 変更が更新されない


markdown_extensions:
    - admonition
    - codehilite

nav:
- Introduction: index.md
- About VketCloudSDK :
    - Setup Account: Unity/SetupAccount.md
    - Operating Environment : Unity/OperatingEnvironment.md
    #- Setup SDK(internal) : Unity/SetupSDK_internal.md
    - Setup SDK(external) : Unity/SetupSDK_external.md
    - Build And Run : Unity/BuildAndRun.md
    - World Upload : Unity/WorldUpload.md
- HEOComponent:
    - HEOWorldSetting: Unity/HEOWorldSetting.md
    - HEOField: Unity/HEOField.md
    - HEOPlayer: Unity/HEOPlayer.md
    - HEOObject: Unity/HEOObject.md
    - HEOAudio: Unity/HEOAudio.md
    - HEOPlane: Unity/HEOPlane.md
    - HEOTextPlane: Unity/HEOTextPlane.md
    - HEOParticle: Unity/HEOParticle.md
    - HEOScript: Unity/HEOScript.md
    - HEOAreacollider: Unity/HEOAreacollider.md
    - HEOVideoTrigger: Unity/HEOVideoTrigger.md
    - HEOActionTrigger: Unity/HEOActionTrigger.md
    - Actions: 
        - Actions Overview: Unity/ActionsOverview.md
        - Openweb: Unity/Openweb.md
        - Play/StopItem: Unity/PlayStopItem.md
        - Show/HideItem: Unity/ShowHideItem.md
        - Play/StopObject: Unity/PlayStopObject.md
        - Show/HideObject: Unity/ShowHideObject.md
        - Show/HideNode: Unity/ShowHideNode.md
        - Enable/DisableClickableNode: Unity/EnableDisableClickableNode.md
        - Enable/DisableCollider: Unity/EnableDisableCollider.md
        - Wait: Unity/Wait.md
        - SetPosRelativePlayer: Unity/SetPosRelativePlayer.md
        - MoveTo: Unity/MoveTo.md
        - Random: Unity/Random.md
        - Warp: Unity/Warp.md
        - JumpWorld: Unity/JumpWorld.md
        - Emote: Unity/Emote.md
        - Motion: Unity/Motion.md
        - NextMotion: Unity/NextMotion.md
        - AddVar: Unity/AddVar.md
        - SetVar: Unity/SetVar.md
        - If A == B: Unity/IfEqual.md
        - If A != B: Unity/IfNotEqual.md
        - If A >= B: Unity/IfGreaterThanOrEqual.md
        - If A <= B: Unity/IfLessThanOrEqual.md
        - StopVideo: Unity/StopVideo.md
        - SetCookieText: Unity/SetCookieText.md
        - OpenComicViewer: Unity/OpenComicViewer.md
        - ShowLayer: Unity/ShowLayer.md
        - CallJavaScript: Unity/CallJavaScript.md
        - Enter/LeaveVoiceGroup: Unity/EnterLeaveVoiceGroup.md
        - WhiteOut/In: Unity/WhiteOutIn.md
        - FadeOut/In: Unity/FadeOutIn.md
- HEOExporter :
    - HEOExporter Overview : heoexporter/he_about_heoexporter.md
    - HEOExporter Tutorial : heoexporter/he_heoexporter_tutorial.md
    - Unity Guidelines : heoexporter/he_UnityGuidelines.md
    - ReflectionProbe : heoexporter/he_ReflectionProbe.md
    - Texture Compression : heoexporter/he_TextureCompression.md
    - Get closer to the look of VketCloud to Unity : heoexporter/he_align_unity_to_vketcloud.md
    - Mesh Collider : heoexporter/he_MeshCollider.md
- Particle Editor :
    - ParticleEditor Overview : particleeditor/pe_about_particleeditor.md
    - About Screen : particleeditor/pe_about_screen.md
    - Operation: particleeditor/pe_control.md
    - Window Info:
      - Toolbar : particleeditor/pe_toolbar.md
      - Property : particleeditor/pe_propertywindow.md
      - Particle List : particleeditor/pe_particlelistwindow.md
- Trouble shooting:
    - Build Error: troubleshooting/BuildError.md
    - Browser is not open: troubleshooting/BrowserNotOpen.md
    - Changes are not applied: troubleshooting/ChangesAreNotApplied.md
- Change Log:
    - v3.2: changelog/changelog-3.2.md
- License: common/License.md

