site_name: VketCloudSDK Manual
site_description: 'VketCloudSDKのマニュアルです'
site_author: 'HIKKY'

theme:
  favicon: images/VketCloudIcon.png
  logo: images/VketCloudIcon.png
  name: material
  language: ja
  palette:
  - scheme: default
    primary: blue
    accent: blue
    toggle:
        icon: material/toggle-switch-off-outline
        name: ダークモードに切り替えます。
  - scheme: slate
    primary: blue
    accent: blue
    toggle:
        icon: material/toggle-switch
        name: ライトモードに切り替えます。
  features:
    - navigation.indexes
    - header.autohide

  analytics:
    gtag: G-05NPW204YY
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s
  nav_style: dark

extra:
  version:
    provider: mike
    default: latest
  search:
    language: 'en'
    language: 'ja'
  homepage: https://www.hikky.co.jp/vketcloud

use_directory_urls: false

plugins:
  - search:
  - mike:
      version_selector: true
      css_dir: css
      javascript_dir: js
      canonical_version: null
  - i18n:
      default_language: ja
      languages:
        en: English
        ja: 日本語
      nav_translations:
        ja:
          Introduction: はじめに
          About VketCloudSDK: VketCloudSDKについて
          Setup Account: アカウント準備
          Operating Environment: 動作環境
          Build And Run: ビルド方法
          World Upload: ワールドアップロード
          Setup SDK: SDKの導入方法
          How to use avatar: アバターの使用方法
          Essential Objects: ワールドの基本要素
          Skybox: スカイボックス設定
          Statements And Flow Control: 文法・制御構文
          Declarations and definitions: 定義・宣言
          Control Statement: 制御構文
          Reference (ref): 参照(ref)
          Constant Variable (const): 定数(const)
          Built-in Types: 組み込み型
          Basic Types: 基本型
          String: 文字列(String)
          List: 配列(List)
          Operator: 演算子
          Class: クラス
          Component: コンポーネント
          Built-in Classes And Functions: 組み込みクラス・関数
          Vector3: Vector3クラス
          Quaternion: Quaternionクラス
          Matrix: Matrixクラス
          Item: Itemクラス
          Player: Playerクラス
          Built-in Functions: 組み込み関数
          System: システム
          Math: 数学
          Network: ネットワーク
          NamePlate: ネームプレート
          GUI: GUI
          HEOExporter: .heoファイルについて
          HEOExporter Tutorial: .heoファイルを出力する
          Unity Guidelines : VketCloudの仕様制限
          ReflectionProbe: 反射を写り込ませるには
          Texture Compression: テクスチャ圧縮
          Auto Texture Compression: 自動テクスチャ圧縮
          Get closer to the look of VketCloud to Unity: UnityとVketCloudの見た目を揃える
          Mesh Collider: メッシュコライダーについて
          HEOComponents: HEOコンポーネント
          About VketCloudSDK: VketCloudSDKについて
          OperatingEnvironment: 動作環境
          SetupSDK: 導入方法
          BuildAndRun: ビルド
          WorldUpload: アップロード
          License: 利用規約
          Loading stops: ブラウザの読み込みが止まる
          Actions: アクションについて
          Actions Overview: アクションの概要
          ActionNodeGraph: アクションノードグラフ
          Particle Editor : パーティクルエディター
          ParticleEditor Overview: パーティクルエディター概要 
          About Screen: 操作画面について
          Operation: 操作説明
          Window Info: ウィンドウ解説
          Toolbar: ツールバー
          Property: プロパティウィンドウ
          Animation Converter : アニメーションコンバーター
          Trouble shooting: トラブルシューティング
          Build Error: ビルドエラー
          Browser is not open: ブラウザが立ち上がらない
          Changes are not applied: 変更が更新されない
          First Step: ワールド制作の基本
          Change Log: チェンジログ
          HeliScript: ヘリスクリプト
          Statements and flow control: 宣言と制御
          Check Tool: チェックツール
          World Making Guide: ワールド制作ガイド
          Avatar File: アバターファイル
          Utility Tools: 補助ツールの使い方
          Login SDK: SDKにログインする

markdown_extensions:
    - admonition
    - codehilite
    - attr_list

nav:
- Introduction: index.md
- About VketCloudSDK:
    - Setup Account : AboutVketCloudSDK/SetupAccount.md
    - Operating Environment : AboutVketCloudSDK/OperatingEnvironment.md
    - Setup SDK : AboutVketCloudSDK/SetupSDK_external.md
    - Login SDK: AboutVketCloudSDK/LoginSDK.md
    - How to use avatar : AboutVketCloudSDK/SetupAvatar.md
- First Step:
    - Essential Objects : FirstStep/WorldBasicComponents.md
    - Build And Run : FirstStep/BuildAndRun.md
    - World Upload : FirstStep/WorldUpload.md
- World Making Guide:
    - Unity Guidelines : WorldMakingGuide/he_UnityGuidelines.md
    - Skybox : WorldMakingGuide/Skybox.md 
    - How to Set Collider : WorldMakingGuide/Collider.md 
    - ReflectionProbe : WorldMakingGuide/ReflectionProbe.md
    - Avatar File: WorldMakingGuide/AvatarFile.md
    - HEOExporter Tutorial : WorldMakingGuide/HEOExporter_Tutorial.md
    - Check Tool: checktool/checktool.md
    - Auto Texture Compression: AutoTextureCompresser/AutoTextureCompresser.md
    - Texture Compression : heoexporter/he_TextureCompression.md
    - Particle Editor :
      - ParticleEditor Overview : particleeditor/pe_about_particleeditor.md
      - About Screen : particleeditor/pe_about_screen.md
      - Operation: particleeditor/pe_control.md
      - Window Info:
        - Toolbar : particleeditor/pe_toolbar.md
        - Property : particleeditor/pe_propertywindow.md
        - Particle List : particleeditor/pe_particlelistwindow.md
    - Animation Converter : HEMAnimationConverter/AnimationConverter.md
- HEOComponents:
    - HEOWorldSetting: HEOComponents/HEOWorldSetting.md
    - HEOField: Unity/HEOField.md
    - HEOPlayer: Unity/HEOPlayer.md
    - HEOObject: Unity/HEOObject.md
    - HEOLODLevel: Unity/HEOLODLevel.md
    - HEOAudio: Unity/HEOAudio.md
    - HEOPlane: Unity/HEOPlane.md
    - HEOUVScroller: Unity/HEOUVScroller.md
    - HEOTextPlane: Unity/HEOTextPlane.md
    - HEOParticle: Unity/HEOParticle.md
    - HEOReflectionProbe : Unity/HEOReflectionProbe.md
    - HEOScript: Unity/HEOScript.md
    - HEOMeshCollider: HEOComponents/HEOMeshCollider.md
    - HEODespawnHeight: Unity/HEODespawnHeight.md
    - HEOCollider: Unity/HEOCollider.md
    - HEOAnimation: Unity/HEOAnimation.md
    - HEOShowFlag : Unity/HEOShowFlag.md
    - HEOAreacollider: Unity/HEOAreacollider.md
    - HEOVideoTrigger: Unity/HEOVideoTrigger.md
    - HEOActionTrigger: Unity/HEOActionTrigger.md
- Actions: 
    #- ActionNodeGraph: Unity/ActionNodeGraph.md #整備のために一旦取り下げ
    - Actions Overview: Unity/ActionsOverview.md
    - Openweb: Unity/Openweb.md
    - Play/StopItem: Unity/PlayStopItem.md
    - Show/HideItem: Unity/ShowHideItem.md
    - Play/StopObject: Unity/PlayStopObject.md
    - Show/HideObject: Unity/ShowHideObject.md
    - Show/HideNode: Unity/ShowHideNode.md
    - Enable/DisableClickableNode: Unity/EnableDisableClickableNode.md
    - Enable/DisableCollider: Unity/EnableDisableCollider.md
    - Wait: Unity/Wait.md
    - SetPosRelativePlayer: Unity/SetPosRelativePlayer.md
    - MoveTo: Unity/MoveTo.md
    - Random: Unity/Random.md
    - Warp: Unity/Warp.md
    - JumpWorld: Unity/JumpWorld.md
    - Emote: Unity/Emote.md
    - Motion: Unity/Motion.md
    - NextMotion: Unity/NextMotion.md
    - AddVar: Unity/AddVar.md
    - SetVar: Unity/SetVar.md
    - If A == B: Unity/IfEqual.md
    - If A != B: Unity/IfNotEqual.md
    - If A >= B: Unity/IfGreaterThanOrEqual.md
    - If A <= B: Unity/IfLessThanOrEqual.md
    - StopVideo: Unity/StopVideo.md
    - SetCookieText: Unity/SetCookieText.md
    - OpenComicViewer: Unity/OpenComicViewer.md
    - ShowLayer: Unity/ShowLayer.md
    - CallJavaScript: Unity/CallJavaScript.md
    - Enter/LeaveVoiceGroup: Unity/EnterLeaveVoiceGroup.md
    - WhiteOut/In: Unity/WhiteOutIn.md
    - FadeOut/In: Unity/FadeOutIn.md
- HeliScript:
    - Built-in Types:
        - Basic Types: hs/hs_var.md
        - String: hs/hs_string.md
        - List: hs/hs_list.md
    - Class: hs/hs_class.md
    - Component: hs/hs_component.md
    - Built-in Classes And Functions:
        - Vector3: hs/hs_struct_vector3.md
        - Quaternion: hs/hs_struct_quaternion.md
        - Matrix: hs/hs_struct_matrix.md
        - Item: hs/hs_class_item.md
        - Player: hs/hs_class_player.md
    - Built-in Functions:
        - System: hs/hs_system_function.md
        - Math: hs/hs_system_function_math.md
        - Network: hs/hs_system_function_net.md
        - NamePlate: hs/hs_system_function_nameplate.md
        - JavaScript: hs/hs_system_function_js.md
        - GUI: hs/hs_system_function_gui.md
    - Statements and flow control:
        - Declarations and definitions: hs/hs_statement_def.md
        - Control Statement: hs/hs_statement_constrol.md
        - Operator: hs/hs_operator.md
- Trouble shooting:
    - Build Error: troubleshooting/BuildError.md
    - Browser is not open: troubleshooting/BrowserNotOpen.md
    - Changes are not applied: troubleshooting/ChangesAreNotApplied.md
    - Get closer to the look of VketCloud to Unity : heoexporter/he_align_unity_to_vketcloud.md
- Change Log:
    - v4.1: changelog/changelog-4.1.md
    - v4.0: changelog/changelog-4.0.md
    - v3.9: changelog/changelog-3.9.md  
    - v3.8: changelog/changelog-3.8.md
    - v3.7: changelog/changelog-3.7.md
    - v3.6: changelog/changelog-3.6.md
    - v3.5: changelog/changelog-3.5.md
    - v3.4: changelog/changelog-3.4.md
    - v3.3: changelog/changelog-3.3.md
    - v3.2: changelog/changelog-3.2.md
- License: common/License.md
